# Generated by Django 3.2.8 on 2021-10-14 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mileage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mileage',
            options={'ordering': ['spare_part'], 'verbose_name': 'Пробег', 'verbose_name_plural': 'Пробег'},
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(db_index=True, max_length=40, verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model_name',
            field=models.CharField(db_index=True, max_length=60, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model_variant',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Модификация'),
        ),
        migrations.AlterField(
            model_name='mileage',
            name='mileage',
            field=models.SmallIntegerField(verbose_name='Пробег, тыс.км'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='brand',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='number',
            field=models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Номер'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nikname', models.CharField(max_length=30, verbose_name='Никнейм')),
                ('drive2_link', models.URLField(blank=True, verbose_name='Ссылка на профиль Drive2.ru')),
                ('cars', models.ManyToManyField(blank=True, to='mileage.Car', verbose_name='Мои автомобили')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профиль',
                'ordering': ['id'],
            },
        ),
    ]
