# Generated by Django 3.2.8 on 2021-10-14 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mileage', '0002_auto_20211014_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='mileage',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Владелец'),
            preserve_default=False,
        ),
    ]
