# Generated by Django 3.2.8 on 2021-10-15 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mileage', '0003_mileage_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nikname',
        ),
    ]
