# Generated by Django 3.2.8 on 2021-10-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mileage', '0004_remove_profile_nikname'),
    ]

    operations = [
        migrations.AddField(
            model_name='mileage',
            name='rating',
            field=models.CharField(choices=[(1, 'Ужасно'), (2, 'Плохо'), (3, 'Сносно'), (4, 'Хорошо'), (5, 'Отлично')], default=0, max_length=1, verbose_name='Рейтинг'),
        ),
    ]
