# Generated by Django 3.2.8 on 2021-10-26 10:08

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('mileage', '0005_mileage_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(db_index=True, max_length=40, verbose_name='Марка')),
            ],
            options={
                'verbose_name': 'Марка авто',
                'verbose_name_plural': 'Марки авто',
                'ordering': ['brand'],
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(db_index=True, max_length=60, verbose_name='Модель')),
                ('brand_id', models.SmallIntegerField(verbose_name='ID марки')),
            ],
            options={
                'verbose_name': 'Модель авто',
                'verbose_name_plural': 'Модели авто',
                'ordering': ['brand_id'],
            },
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['brand', 'model_name'], 'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.RemoveField(
            model_name='car',
            name='age',
        ),
        migrations.RemoveField(
            model_name='car',
            name='model_variant',
        ),
        migrations.AddField(
            model_name='car',
            name='generation',
            field=models.CharField(db_index=True, default=2, max_length=100, verbose_name='Поколение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mileage',
            name='rating',
            field=models.CharField(choices=[(1, 'Ужасно'), (2, 'Плохо'), (3, 'Сносно'), (4, 'Хорошо'), (5, 'Отлично')], default=3, max_length=1, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mileage.carbrand', verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model_name',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='brand', chained_model_field='brand', on_delete=django.db.models.deletion.CASCADE, to='mileage.carmodel'),
        ),
    ]
