# Generated by Django 3.2.8 on 2021-10-29 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mileage', '0005_mileage_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(db_index=True, max_length=40, verbose_name='Марка')),
            ],
            options={
                'verbose_name': 'Марка авто',
                'verbose_name_plural': 'Марки авто',
                'ordering': ['brand'],
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(db_index=True, max_length=60, verbose_name='Модель')),
                ('brand_id', models.SmallIntegerField(verbose_name='ID марки')),
            ],
            options={
                'verbose_name': 'Модель авто',
                'verbose_name_plural': 'Модели авто',
                'ordering': ['brand_id'],
            },
        ),
        migrations.CreateModel(
            name='SparePartCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория запчасти',
                'verbose_name_plural': 'Категории запчастей',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='mileage',
            options={'ordering': ['spare_part'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='sparepart',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Запчасть', 'verbose_name_plural': 'Запчасти'},
        ),
        migrations.RemoveField(
            model_name='mileage',
            name='car',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cars',
        ),
        migrations.AddField(
            model_name='mileage',
            name='review',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='mileage',
            name='rating',
            field=models.CharField(choices=[(1, 'Ужасно'), (2, 'Плохо'), (3, 'Сносно'), (4, 'Хорошо'), (5, 'Отлично')], default=3, max_length=1, verbose_name='Рейтинг'),
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.AddField(
            model_name='mileage',
            name='car_brand',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='mileage.carbrand', verbose_name='Марка авто'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mileage',
            name='car_model',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='mileage.carmodel', verbose_name='Модель авто'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sparepart',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='mileage.sparepartcategory', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
