# Generated by Django 3.2.8 on 2021-10-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mileage', '0008_auto_20211031_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbrand',
            name='brand',
            field=models.CharField(choices=[], db_index=True, max_length=40, unique=True, verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('1', 'Ужасно'), ('2', 'Плохо'), ('3', 'Сносно'), ('4', 'Хорошо'), ('5', 'Отлично')], default=3, max_length=1, verbose_name='Рейтинг'),
        ),
    ]
