# Generated by Django 3.2.8 on 2021-11-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mileage', '0010_auto_20211109_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbrand',
            name='logo',
            field=models.ImageField(blank=True, upload_to='media/logo/', verbose_name="Эмблема'"),
        ),
    ]
