# Generated by Django 3.2.8 on 2021-12-01 18:10

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('mileage', '0015_auto_20211126_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='jpeg',
            field=stdimage.models.JPEGField(blank=True, upload_to='reviews/'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comment', to='mileage.review', verbose_name='Отзыв'),
        ),
    ]
