# Generated by Django 3.2.8 on 2022-03-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mileage', '0016_auto_20211201_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbrand',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logo/', verbose_name='Эмблема'),
        ),
    ]
